OnlineShop/Areas/Customer/Controllers/OrderController.cs
using BusinessLogic.DtoModels;
using BusinessLogic.Interfaces;
using BusinessLogic.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OnlineShop.Areas.Customer.Models;
using OnlineShop.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace OnlineShop.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class OrderController : Controller
    {
        private readonly IProductManager _productManager;
        private readonly IOrderManager _orderManager;

        private readonly ICustomGenericService<Dto_PaymentType> _paymentTypesManager;
        private readonly ICustomGenericService<Dto_DeliveryType> _deliveryTypesManeger;
        private readonly ICustomGenericServiceAsync<Dto_DeliveryDetails> _deliveryManager;
        private readonly ICustomGenericServiceAsyncMembers<Dto_DeliveryStatus> _deliveryStatusManager;

        private readonly IProductReviewManager _productReviewManager;
        private readonly IProductSpecManager _productSpecManager;
        private readonly IApplicationUserManager _userManager;
        private readonly IProductTypesManager _productTypesManager;

        private readonly IHttpContextAccessor _httpContextAccessor;

        public OrderController(IProductManager productManager,
            IOrderManager orderManager,
            ICustomGenericService<Dto_PaymentType> paymentTypesManager,
            ICustomGenericService<Dto_DeliveryType> deliveryTypesManeger,
            ICustomGenericServiceAsync<Dto_DeliveryDetails> deliveryManager,
            ICustomGenericServiceAsyncMembers<Dto_DeliveryStatus> deliveryStatusManager,
            IProductReviewManager productReviewManager,
            IProductSpecManager productSpecManager,
            IApplicationUserManager userManager,
            IProductTypesManager productTypesManager,
            IHttpContextAccessor httpContextAccessor)
        {
            _productManager = productManager;
            _orderManager = orderManager;
            _paymentTypesManager = paymentTypesManager;
            _deliveryTypesManeger = deliveryTypesManeger;
            _deliveryManager = deliveryManager;
            _productReviewManager = productReviewManager;
            _productSpecManager = productSpecManager;
            _userManager = userManager;
            _productTypesManager = productTypesManager;
            _deliveryStatusManager = deliveryStatusManager;
            _httpContextAccessor = httpContextAccessor;
        }
        
        [HttpGet]
        public IActionResult Checkout()
        {
            var products = HttpContext.Session.Get<List<Dto_Product>>("products");
            ViewData["deliveryTypes"] = new SelectList(_deliveryTypesManeger.GetAllObjects(), "Id", "Name");
            ViewData["paymentTypes"] = new SelectList(_paymentTypesManager.GetAllObjects(), "Id", "Name");
            if (products == null)
            {
                return RedirectToAction(nameof(EmptyCart));
            }
            if (products.Count == 0)
            {
                return RedirectToAction(nameof(EmptyCart));
            }
            HttpContext.Session.Set("deliveryTypes", _deliveryTypesManeger.GetAllObjects());
            HttpContext.Session.Set("payTypes", _paymentTypesManager.GetAllObjects());
            return View();
        }

        [HttpGet]
        public IActionResult EmptyCart()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Checkout(OrderModel anOrder)
        {
            var products = HttpContext.Session.Get<List<Dto_Product>>("products");
            if (products != null)
            {
                foreach (var product in products)
                {
                    Dto_OrderDetails orderDetails = new()
                    {
                        ProductId = product.Id,                      
                    };
                    anOrder.Order.OrderDetails.Add(orderDetails);
                }

                Dto_DeliveryDetails deliveryDetails = anOrder.Delivery;

                anOrder.Order.DeliveryDetails = deliveryDetails;
                anOrder.Order.DeliveryDetails.IsBusyShipping = false;
                if (anOrder.Order.DeliveryDetails.PaymentTypeId == 4)
                    anOrder.Order.DeliveryDetails.DeliveryStatusId = 8;
                else
                    anOrder.Order.DeliveryDetails.DeliveryStatusId = 1;

            }
            else
            {
                return Redirect("/Customer/Home");
            }


            anOrder.Order.OrderDate = DateTime.Now;
            anOrder.Order.OrderNo = GetOrderNo();
            var ordId = await _orderManager.AddOrder(anOrder.Order);

            anOrder.Delivery.OrderId = ordId;
            await _deliveryManager.CreateObjectAsync(anOrder.Order.DeliveryDetails);

            HttpContext.Session.Set("products", new List<Dto_Product>());
            return RedirectToAction(nameof(Invoice), new { id = ordId });
        }


        public string GetOrderNo()
        {
            int rowCount = _orderManager.GetGeneralOrderCount();
            return rowCount.ToString("000");
        }


        [HttpGet]
        public IActionResult Invoice(int id)
        {
            var model = _orderManager.GetOrderById(id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Pay(int? id)
        {
            var model = _orderManager.GetOrderById((int)id);
            if (model == null)
            {
                return NotFound();
            }
            model.DeliveryDetails.DeliveryStatusId = 1;
            await _orderManager.UpdateOrder(model);
            return View(model);
        }

        [HttpPost]
        public IActionResult Pay()
        {
            TempData["save"] = "Purchase paid";
            return RedirectToAction("Index", "Home");
        }

        [ActionName("Remove")]
        public IActionResult RemoveToCart(int? id)
        {
            var products = HttpContext.Session.Get<List<Dto_Product>>("products");
            if (products != null)
            {
                var product = products.FirstOrDefault(c => c.Id == id);
                if (product != null)
                {
                    products.Remove(product);
                    HttpContext.Session.Set("products", products);
                }
            }

            return products.Count == 0 ? RedirectToAction(nameof(EmptyCart)) :
                RedirectToAction(nameof(Checkout));
        }

        [HttpPost]
        public IActionResult Remove(int? id)
        {
            var products = HttpContext.Session.Get<List<Dto_Product>>("products");
            if (products != null)
            {
                var product = products.FirstOrDefault(c => c.Id == id);
                if (product != null)
                {
                    products.Remove(product);
                    HttpContext.Session.Set("products", products);
                }
            }
            return RedirectToAction(nameof(Checkout));
        }


        public IActionResult Cart()
        {
            var products = HttpContext.Session.Get<List<Dto_Product>>("products");
            if (products == null)
            {
                products = new List<Dto_Product>();
            }
            return View(products);
        }

        [HttpPost]
        public async Task<IActionResult> AddToCart(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = _productManager.GetFullProductById(id);
            if (product == null)
            {
                return NotFound();
            }

            var products = HttpContext.Session.Get<List<Dto_Product>>("products");
            if (products == null)
            {
                products = new List<Dto_Product>();
            }


            products.Add(product);
            HttpContext.Session.Set("products", products);

            TempData["Save"] = "Added to cart";

            if (HttpContext.Session.Get<bool>("IsFromDetails") == true)
                return RedirectToAction("Detail", "Home", new { id = id });
            else
                return RedirectToAction("Index", "Home");

        }

        [HttpGet]
        public IActionResult MyOrders()
        {
            var email = _httpContextAccessor.HttpContext.User.Identity.Name;
            if (email == null)
            {
                return RedirectToAction(nameof(NoOrders));
            }
            var result = _orderManager.GetOrdersByEmail(email);
            if (result == null)
            {
                return RedirectToAction(nameof(NoOrders));
            }
            if (result.Count() == 0)
            {
                return RedirectToAction(nameof(NoOrders));
            }
            return View(result);
        }

        [HttpGet]
        public IActionResult NoOrders()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Cancel(int id)
        {
            var model = _orderManager.GetOrderById((int)id);
            if (model == null)
            {
                return NotFound();
            }
            await _orderManager.DeleteOrder(model);
            TempData["save"] = "The order was deleted successfully";
            return RedirectToAction(nameof(MyOrders));
        }
    }
}

OnlineShop/Areas/Customer/Controllers/SearchController.cs
using BusinessLogic.DtoModels;
using BusinessLogic.Interfaces;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Areas.Customer.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace OnlineShop.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class SearchController : Controller
    {
        private readonly IProductManager _productManager;
        private readonly IProductReviewManager _productReviewManager;
        private readonly IProductSpecManager _productSpecManager;
        private readonly IApplicationUserManager _userManager;
        private readonly IProductTypesManager _productTypesManager;

        public SearchController(IProductManager productManager,
            IProductReviewManager productReviewManager,
            IProductSpecManager productSpecManager,
            IApplicationUserManager userManager,
            IProductTypesManager productTypesManager)
        {
            _productManager = productManager;
            _productReviewManager = productReviewManager;
            _productSpecManager = productSpecManager;
            _userManager = userManager;
            _productTypesManager = productTypesManager;
        }

        public async Task<IActionResult> SearchIndex(int? page, string searchString)
        {
            List<Dto_Product> products = _productManager.FindFullProductsThatContainName(searchString).ToList();
            if (products == null)
            {
                return NotFound();
            }
            ViewBag.SearchString = searchString;
            return View(products.ToPagedList(page ?? 1, 5));
        }

        public async Task<IActionResult> Products(int? page)
        {
            var result = _productManager.GetFullProducts().ToPagedList(page ?? 1, 5);
            return View(result);
        }

        public async Task<IActionResult> SearchByProductType(int? page, int? id)
        {
            if (id == null)
                return NotFound();
            var products = _productManager.GetProductsByProductType((int)id).ToList();

            if (products == null)
            {
                return NotFound();
            }

            string type = _productTypesManager.FindProductType(id).ProductType;
            ViewBag.TypeString = type ?? "Category";
            return View(products.ToPagedList(page ?? 1, 5));

        }
    }
}

OnlineShop/Areas/Customer/Views/Home/Detail.cshtml
@model BusinessLogic.DtoModels.Dto_Product
@{
	ViewData["Title"] = "Details";

	var _reviews = HttpContextAccessor.HttpContext.Session.Get<Dictionary<string, Dictionary<string, string>>>("reviews");
	var _specs = HttpContextAccessor.HttpContext.Session.Get<Dictionary<string, Dictionary<string, string>>>("specs");

	var _rate = ViewData["reviewRate"] as double?;
	var _desc = ViewData["productDesc"] as string[];

	var _rateof5 = ViewData["rateof5"] as int[];
	var _rateof4 = ViewData["rateof4"] as int[];
	var _rateof3 = ViewData["rateof3"] as int[];
	var _rateof2 = ViewData["rateof2"] as int[];
	var _rateof1 = ViewData["rateof1"] as int[];

	HttpContextAccessor.HttpContext.Session.Set("IsFromDetails", true);
}

@using BusinessLogic.Services
@using BusinessLogic.DtoModels
@using OnlineShop.Utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{
    List<Dto_Product> products = HttpContextAccessor.HttpContext.Session.Get<List<Dto_Product>>("products");
    Dto_Product product = null;
    if (products != null)
    {
        product = products.FirstOrDefault(c => c.Id == Model.Id);
    }
}

<!-- SECTION -->
<div class="section">
	<!-- container -->
	<div class="container">
		<!-- row -->
		<div class="row">
			<!-- Product main img -->
			<div class="col-md-5 col-md-push-2"> <!-- TODO -->
				<div id="product-main-img">
					<div class="product-preview">
						<img src="~/@Model.Image" alt="~/Images/noimage.png">
					</div>

					<div class="product-preview">
						<img src="~/Images/noimage.png" alt="~/Images/noimage.png">
					</div>

					<div class="product-preview">
						<img src="~/Images/noimage.png" alt="~/Images/noimage.png">
					</div>

					<div class="product-preview">
						<img src="~/Images/noimage.png" alt="~/Images/noimage.png">
					</div>
				</div>
			</div>
			<!-- /Product main img -->

			<!-- Product thumb imgs -->
			<div class="col-md-2  col-md-pull-5"> <!-- TODO -->
				<div id="product-imgs">
					<div class="product-preview">
						<img src="~/@Model.Image" alt="~/Images/noimage.png">
					</div>

					<div class="product-preview">
						<img src="~/Images/noimage.png" alt="~/Images/noimage.png">
					</div>

					<div class="product-preview">
						<img src="~/Images/noimage.png" alt="~/Images/noimage.png">
					</div>

					<div class="product-preview">
						<img src="~/Images/noimage.png" alt="~/Images/noimage.png">
					</div>
				</div>
			</div>
			<!-- /Product thumb imgs -->

			<!-- Product details -->
			<div class="col-md-5">
				<div class="product-details">
					<h2 class="product-name">@Model.Name</h2>
					<div>
						<div class="product-rating">
							@if (_rate != null)
							{
								@for (int i = 0; i < 5; i++)
								{
									@if (i < _rate)
									{
										<i class="fa fa-star"></i>
									}
									else
									{
										<i class="fa fa-star-o"></i>
									}
								}
							}
						</div>
						@if (_rate != null)
						{
						<a class="review-link" href="#">@_reviews.Count()
							Review(s) | Add your review</a>
						}

					</div>
					<div>
						<h3 class="product-price">$@Model.Price <del class="product-old-price">$@Math.Round(Model.Price + Model.Price * 0.1m, 2)</del></h3>
						@if (@Model.IsAvailable)
						{
							<span class="product-available">In Stock</span>
						}
						else
						{
							<span class="product-notavailable">Out of Stock</span>
						}
					</div>
					@if (_desc != null)
					{
						<p>@(_desc[0])...<a class="review-link" href="#">More description</a></p>
					}
					

					<div class="add-to-cart form-group">
						<div class="qty-label">
							Qty
							<div class="input-number">
								<input type="number">
								<span class="qty-up">+</span>
								<span class="qty-down">-</span>
							</div>
						</div>

						@if (Model.IsAvailable)
						{
							@if (product != null) 
							{
								<form asp-action="Remove" asp-controller="Order" asp-route-id="@Model.Id" enctype="multipart/form-data">
									<button style="width:300px;margin-top:15px" type="submit" class="add-to-cart-btn form-control">
										<i class="fa-solid fa-xmark"></i>
										Remove from Cart
									</button>
								</form>
							}
							else
							{

								<button style="width:300px;margin-top:15px" onclick="addToCart(@Model.Id)" type="submit" class="add-to-cart-btn form-control">
									<i class="fa-solid fa-shopping-cart"></i>
									Add to Cart
								</button>
							}
						}
					</div>

					<div class="add-to-cart form-group">

						<button onclick="addToWishlist(@Model.Id)" style="width:300px; border-color: #D10024; color: #000; background-color: #FFF; margin-top:15px" type="submit" class="add-to-cart-btn form-control">
							<i class="fa-solid fa-heart"></i>
							Add to wishlist
						</button>
					</div>





					<ul class="product-btns">
						<li>
							<a class="btn-link" onclick="addToWishlist(@Model.Id)"><i class="fa-solid fa-heart-o"></i> add to wishlist</a>
						</li>
					</ul>

					<ul class="product-links">
						<li>Category:</li>
						<li><a href="#">@Model.ProductTypes.ProductType</a></li>
						<li><a href="#">@Model.SpecialTag.Name</a></li>
					</ul>
				</div>
			</div>
			<!-- /Product details -->

			<!-- Product tab -->
			<div class="col-md-12">
				<div id="product-tab">
					<!-- product tab nav -->
					<ul class="tab-nav">
						<li id="a1" class="active"><a data-toggle="tab" href="#tab1" onclick={fade1()}>Description</a></li>
						<li id="a2" class=""><a data-toggle="tab" href="#tab2" onclick={fade2()}>Details</a></li>
						<li id="a3" class=""><a data-toggle="tab" href="#tab3" onclick={fade3()}>Reviews</a></li>
					</ul>
					<!-- /product tab nav -->

					<!-- product tab content -->
					<div class="tab-content">
						<!-- tab1  -->
						<div id="tab1" class="tab-pane fade in active">
							<div class="row">
								<div class="col-md-12">
									@if (_desc != null)
									{
										@foreach (var item in _desc)
										{
											<p>@item</p>
											<br/>
										}
									}
									else
									{
										<p>No description</p>
									}
								</div>
							</div>
						</div>
						<!-- /tab1  -->

						<!-- tab2  -->
						<div id="tab2" class="tab-pane fade in">
							<div class="row">
								<div class="col-md-12">
								@if (_specs != null)
								{
									@foreach (var item in _specs)
									{
										<h2>@item.Key</h2>
										<table class="table border">       
											<tbody>

												@foreach (var itemInfo in item.Value)
												{
													<tr>
														<td class="col-md-2">@itemInfo.Key</td>
														<td class="col-md-2">@itemInfo.Value</td>
													</tr>
												}

											</tbody>
										</table>
									}
								}
								else
								{
									<p>No description</p>
								}
								</div>
							</div>
						</div>
						<!-- /tab2  --> <!-- TODO -->

						<!-- tab3  -->
						<div id="tab3" class="tab-pane fade in">
							<div class="row">
								<!-- Rating -->
								<div class="col-md-3">
									<div id="rating">
										<div class="rating-avg">
											<span>@_rate</span>
											<div class="rating-stars">
												@if (_rate != null)
												{
													@for (int i = 0; i < 5; i++)
													{
														@if (i < _rate)
														{
															<i class="fa fa-star"></i>
														}
														else
														{
															<i class="fa fa-star-o"></i>
														}
													}
												}
											</div>
										</div>


										<ul class="rating">
											<li>
												<div class="rating-stars">
													<i class="fa-solid fa-star"></i>
													<i class="fa-solid fa-star"></i>
													<i class="fa-solid fa-star"></i>
													<i class="fa-solid fa-star"></i>
													<i class="fa-solid fa-star"></i>
												</div>
												<div class="rating-progress">
													<div style="width: @_rateof5[1]%;"></div>
												</div>
												<span class="sum">@_rateof5[0]</span>
											</li>
											<li>
												<div class="rating-stars">
													<i class="fa-solid fa-star"></i>
													<i class="fa-solid fa-star"></i>
													<i class="fa-solid fa-star"></i>
													<i class="fa-solid fa-star"></i>
													<i class="fa-regular fa-star"></i>
												</div>
												<div class="rating-progress">
													<div style="width: @_rateof4[1]%;"></div>
												</div>
												<span class="sum">@_rateof4[0]</span>
											</li>
											<li>
												<div class="rating-stars">
													<i class="fa-solid fa-star"></i>
													<i class="fa-solid fa-star"></i>
													<i class="fa-solid fa-star"></i>
													<i class="fa-regular fa-star"></i>
													<i class="fa-regular fa-star"></i>
												</div>
												<div class="rating-progress">
													<div style="width: @_rateof3[1]%"></div>
												</div>
												<span class="sum">@_rateof3[0]</span>
											</li>
											<li>
												<div class="rating-stars">
													<i class="fa-solid fa-star"></i>
													<i class="fa-solid fa-star"></i>
													<i class="fa-regular fa-star"></i>
													<i class="fa-regular fa-star"></i>
													<i class="fa-regular fa-star"></i>
												</div>
												<div class="rating-progress">
													<div style="width: @_rateof2[1]%"></div>
												</div>
												<span class="sum">@_rateof2[0]</span>
											</li>
											<li>
												<div class="rating-stars">
													<i class="fa-solid fa-star"></i>
													<i class="fa-regular fa-star"></i>
													<i class="fa-regular fa-star"></i>
													<i class="fa-regular fa-star"></i>
													<i class="fa-regular fa-star"></i>
												</div>
												<div class="rating-progress">
													<div style="width: @_rateof1[1]%"></div>
												</div>
												<span class="sum">@_rateof1[0]</span>
											</li>
										</ul>
									</div>
								</div>
								<!-- /Rating -->

								<!-- Reviews -->
								<div class="col-md-6">
									<div id="reviews">
										<ul class="reviews">
											@if (_reviews != null)
											{
												@foreach (var item in _reviews)
												{
													<li>
														<div class="review-heading">
															<h5 class="name">@item.Value["Name"]</h5>
															<p class="date">@item.Value["ReviewDate"]</p>
															<div class="review-rating">
																@for (int i = 0; i < int.Parse(@item.Value["Rate"]); i++)
																{
																	<i class="fa fa-star"></i>
																}
																@for (int i = int.Parse(@item.Value["Rate"]); i < 5; i++)
																{
																	<i class="fa fa-star-o empty"></i>
																}
															</div>
														</div>
														<div class="review-body">
															<p>@item.Value["RewiewText"]</p>
														</div>
													</li>
												}
											}
											else
											{
												
											}
										</ul>
									</div>
								</div>
								<!-- /Reviews -->

								<!-- Review Form -->
								<div class="col-md-3">
									<div id="review-form">
										<form class="review-form">
											<input class="input" type="text" placeholder="Your Name">
											<input class="input" type="email" placeholder="Your Email">
											<textarea class="input" placeholder="Your Review"></textarea>
											<div class="input-rating">
												<span>Your Rating: </span>
												<div class="stars">
													<input id="star5" name="rating" value="5" type="radio"><label for="star5"></label>
													<input id="star4" name="rating" value="4" type="radio"><label for="star4"></label>
													<input id="star3" name="rating" value="3" type="radio"><label for="star3"></label>
													<input id="star2" name="rating" value="2" type="radio"><label for="star2"></label>
													<input id="star1" name="rating" value="1" type="radio"><label for="star1"></label>
												</div>
											</div>
											<button class="primary-btn">Submit</button>
										</form>
									</div>
								</div>
								<!-- /Review Form -->
							</div>
						</div>
						<!-- /tab3  -->
					</div>
					<!-- /product tab content  -->
				</div>
			</div>
			<!-- /product tab -->
		</div>
		<!-- /row -->
	</div>
	<!-- /container -->
</div>
<!-- /SECTION -->


@section Scripts{
    @{ 
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
        await Html.RenderPartialAsync("_AntiValidationScriptsPartial");
		await Html.RenderPartialAsync("_FadeInformationPartial");
    }
	<script>fade1()</script>
	<script src="//cdn.jsdelivr.net/npm/alertifyjs@1.11.2/build/alertify.min.js"></script>
	<script type="text/javascript">

	function addToCart(num) {

		console.log('Add to cart');
		console.log(num)
		$.ajax({
			type: "POST",
			url: "/Customer/Order/AddToCart",
			data: {id: num},
		});
		var index = $('#cardBadge').text();
		console.log(index);
		$('#cardBadge').text(parseInt(index) + parseInt(1));
        alertify.success('Added to cart');
    }

	function addToWishlist(num) {

		console.log('Add to wishlist');
		console.log(num)
		$.ajax({
			type: "POST",
			url: "/Customer/Home/AddToWishlist",
			data: {id: num},
		});
		var index = $('#wishlistBadge').text();
		console.log(index);
		$('#wishlistBadge').text(parseInt(index) + parseInt(1));
        alertify.success('Added to wishlist');
    }
	</script>
}

OnlineShop/Areas/Customer/Views/Home/EmptyWishlist.cshtml
<link rel="stylesheet" type="text/css" href="~/css/cart.css" />

<section just-grey">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card" style="border-radius: 15px;">
          <div class="card-body p-5">

            <div class="text-center mb-0">
            <p class="pb-3">
                <span class="lead font-italic">Your wishlist is empty</span>
            </p>

            <figcaption class="blockquote-footer mb-0">
                <a asp-action="Index" asp-controller="Home">Back to shop</a>
              </figcaption>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

OnlineShop/Areas/Customer/Views/Home/Index.cshtml
@using BusinessLogic.DtoModels
@using Microsoft.AspNetCore.Http
@using OnlineShop.Utility
@using X.PagedList.Mvc.Core
@using X.PagedList.Web.Common

@model OnlineShop.Areas.Customer.Models.HomeControllerIndexModel
@inject IHttpContextAccessor HttpContextAccessor

<link rel="stylesheet" type="text/css" href="~/css/styleproducts.css"/>

@{
    ViewData["Title"] = "Home";

	var products = HttpContextAccessor.HttpContext.Session.Get<List<Dto_Product>>("products");

    if (products == null)
    {
        products=new List<Dto_Product>();
    }

	HttpContextAccessor.HttpContext.Session.Set("IsFromDetails", false);
}

<br/>

<div>
	<h3 class="text-info">Categories</h3>
	<div class="col-md-12">
		<div class="card-group">
			@foreach (var item in Model.ProductTypes)
			{
				<div class="card shadow-0" style="background-color: #FFF; margin: 10px; width: 10rem;">
					<img class="card-img-top" src="~/@item.Image" alt="~/noImage.png">
					<div class="text-center">
						<form asp-controller="Search" asp-action="SearchByProductType">
							<input type="hidden" value="1" name="Page"/>
							<input type="hidden" value="@item.Id" name="Id"/>

							<button style="padding: 0;" type="submit" class="card-title btn btn-link">
								@item.ProductType
							</button>
						</form>
					</div>
				</div>
			}
		</div>
	</div>
	<br/><hr/><br />
</div>


<div>
	<div class="col-md-12">
		<div class="card-group">
			@foreach(var product in Model.Products)
			{
			<div class="product" style="margin: 10px; width: 16rem;">
				<div class="product-img">
					<img src="~/@product.Image" style="height: 250px; width: 250px" alt="">
				</div>

				<div class="product-body">
					<p class="product-category">
						@product.ProductTypes.ProductType
					</p>

					<h3 class="product-name">
						<a asp-action="Detail" asp-controller="Home" asp-route-id="@product.Id">
							@product.Name
						</a>
					</h3>

					<h4 class="product-price">
						$@product.Price 
						<del class="product-old-price">
							$@Math.Round(product.Price + product.Price * 0.1m, 2)
						</del>	
					</h4>

					<div class="product-btns">
						
						@if (product.IsAvailable)
						{
							<button onclick="addToCart(@product.Id)" class="add-to-compare">
								<i class="fas fa-cart-shopping"></i>
								<span class="tooltipp">add to cart</span>
							</button>
							<input type="hidden" id="cartDataId" name="id" value="@product.Id"/>
						}


							<button onclick="addToWishlist(@product.Id)" class="add-to-wishlist">
								<i class="fas fa-heart"></i>
								<span class="tooltipp">add to wishlist</span>
							</button>
							<input type="hidden" id="wishlistDataId" name="id" value="@product.Id"/>

					</div>
				</div>
			</div>
			}
		</div>
	</div>
</div>


<div>
    @Html.PagedListPager(Model.Products, c => Href("~/Customer/Home/Index?page=" + c), PagedListRenderOptions.Classic)
</div>

@section Scripts{
	<script src="//cdn.jsdelivr.net/npm/alertifyjs@1.11.2/build/alertify.min.js"></script>
	<script type="text/javascript">

	function addToCart(num) {

		console.log('Add to cart');
		console.log(num)
		$.ajax({
			type: "POST",
			url: "/Customer/Order/AddToCart",
			data: {id: num},
		});
		var index = $('#cartBadge').text();
		console.log(index);
		$('#cartBadge').text(parseInt(index) + parseInt(1));
        alertify.success('Added to cart');
    }

	function addToWishlist(num) {

		console.log('Add to wishlist');
		console.log(num)
		$.ajax({
			type: "POST",
			url: "/Customer/Home/AddToWishlist",
			data: {id: num},
		});
		var index = $('#wishlistBadge').text();
		console.log(index);
		$('#wishlistBadge').text(parseInt(index) + parseInt(1));
        alertify.success('Added to wishlist');
    }
        
    $(function(){
        var save = '@TempData["save"]'
        if(save!='') {
            alertify.success(save);
        }
        var edit = '@TempData["edit"]'
        if(edit!='') {
            alertify.success(edit);
        }
        var del = '@TempData["delete"]'
        if (del!='') {
            alertify.error(del);
        }
    })
    </script>
}