OnlineShop/Areas/Admin/Controllers/ProductController.cs
using BusinessLogic.DtoModels;
using BusinessLogic.Interfaces;
using BusinessLogic.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.IO;
using System.Threading.Tasks;

namespace OnlineShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ProductController : Controller
    {
        private readonly IProductManager _productManager;
        private readonly IProductTypesManager _productTypesManager;
        private readonly ISpecialTagManager _specialTagManager;
        private readonly IWebHostEnvironment _he;

        public ProductController(IWebHostEnvironment he,
            IProductTypesManager productTypesManager,
            IProductManager productManager,
            ISpecialTagManager specialTagManager)
        {
            _he = he;
            _productTypesManager = productTypesManager;
            _productManager = productManager;
            _specialTagManager = specialTagManager;
        }
        public IActionResult Index()
        {
            return View(_productManager.GetFullProducts());
        }

        // POST Index Action method
        [HttpPost]
        public IActionResult Index(decimal? lowAmount, decimal? largeAmount)
        {
            var products = _productManager.GetProductsBetweenPrice(lowAmount, largeAmount);
            if (lowAmount == null || largeAmount == null)
            {
                products = _productManager.GetFullProducts();
            }
            return View(products);
        }

        // Get Create method
        public IActionResult Create()
        {
            ViewData["productTypeId"] = new SelectList(_productTypesManager.GetAllProductTypes(), "Id", "ProductType");
            ViewData["TagId"] = new SelectList(_specialTagManager.GetAllSpecialTags(), "Id", "Name");
            return View();
        }

        // Post Create method
        [HttpPost]
        public async Task<IActionResult> Create(Dto_Product product, IFormFile image)
        {
            ModelState.Remove("Image");
            ModelState.Remove("ProductTypes");
            ModelState.Remove("SpecialTag");
            if (ModelState.IsValid)
            {
                var searchProduct = _productManager.GetProductByName(product.Name);
                if (searchProduct != null)
                {
                    ViewBag.message = "This product is already exist";
                    ViewData["productTypeId"] = new SelectList(_productTypesManager.GetAllProductTypes(), "Id", "ProductType");
                    ViewData["TagId"] = new SelectList(_specialTagManager.GetAllSpecialTags(), "Id", "Name");
                    return View(product);
                }

                if (image != null)
                {
                    var name = Path.Combine(_he.WebRootPath + "/Images", Path.GetFileName(image.FileName));
                    await image.CopyToAsync(new FileStream(name, FileMode.Create));
                    product.Image = "Images/" + image.FileName;
                }

                if (image == null)
                {
                    product.Image = "Images/noImage.png";
                }
                await _productManager.AddProduct(product);
                TempData["save"] = "Product has been saved";
                return RedirectToAction(nameof(Index));
            }

            return View(product);
        }

        // GET Edit Action Method
        public ActionResult Edit(int? id)
        {
            ViewData["productTypeId"] = new SelectList(_productTypesManager.GetAllProductTypes(), "Id", "ProductType");
            ViewData["TagId"] = new SelectList(_specialTagManager.GetAllSpecialTags(), "Id", "Name");
            if (id == null)
            {
                return NotFound();
            }

            var product = _productManager.GetFullProductById(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST Edit Action Method
        [HttpPost]
        public async Task<IActionResult> Edit(Dto_Product product, IFormFile image)
        {
            ModelState.Remove("Image");
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    var name = Path.Combine(_he.WebRootPath + "/Images", Path.GetFileName(image.FileName));
                    await image.CopyToAsync(new FileStream(name, FileMode.Create));
                    product.Image = "Images/" + image.FileName;
                }
                if (image == null)
                {
                    if (product.Image == null)
                        product.Image = "Images/noImage.png";
                }

                await _productManager.UpdateProduct(product);
                TempData["edit"] = "Product has been updated";
                return RedirectToAction(nameof(Index));
            }

            return View(product);
        }

        // GET Details Action Method
        public async Task<IActionResult> Details(int? id)
        {
            ViewData["productTypeId"] = new SelectList(_productTypesManager.GetAllProductTypes(), "Id", "ProductType");
            ViewData["TagId"] = new SelectList(_specialTagManager.GetAllSpecialTags(), "Id", "Name");
            if (id == null)
            {
                return NotFound();

            }
            var product = _productManager.GetFullProductById(id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET Delete Action Method
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var product = _productManager.GetFullProductById(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST Delete Action Method
        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var product = _productManager.GetProductByIdWithoutTags(id);
            if (product == null)
            {
                return NotFound();
            }
            await _productManager.RemoveProduct(product);
            TempData["delete"] = "Product has been deleted";
            return RedirectToAction(nameof(Index));
        }
    }
}

OnlineShop/Areas/Admin/Controllers/RoleController.cs
using BusinessLogic.DtoModels;
using BusinessLogic.Interfaces;
using BusinessLogic.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IUserRoleManager _userRoleManager;
        public RoleController(RoleManager<IdentityRole> roleManager,
            UserManager<IdentityUser> userManager,
            IUserRoleManager userRoleManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _userRoleManager = userRoleManager;
        }

        public IActionResult Index()
        {
            var roles = _roleManager.Roles.ToList();
            ViewBag.Roles = roles;
            return View();
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            IdentityRole role = new IdentityRole();
            role.Name = name;
            var isExist = await _roleManager.RoleExistsAsync(role.Name);

            if (isExist)
            {
                ViewBag.mgs = "This role is already exist!";
                ViewBag.name = name;
                return View();
            }
            var result = await _roleManager.CreateAsync(role);
            if (result.Succeeded)
            {
                TempData["Save"] = "Role has been saved successfully";
                return RedirectToAction(nameof(Index));
            }
            return View(result);
        }

        public async Task<IActionResult> Edit(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            ViewBag.id = role.Id;
            ViewBag.name = role.Name;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, string name)
        {

            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            role.Name = name;
            var isExist = await _roleManager.RoleExistsAsync(role.Name);
            if (isExist)
            {
                ViewBag.mgs = "This role is aldeady exist";
                ViewBag.name = name;
                return View();
            }
            var result = await _roleManager.UpdateAsync(role);
            if (result.Succeeded)
            {
                TempData["save"] = "Role has been updated successfully";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }


        public async Task<IActionResult> Delete(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            ViewBag.id = role.Id;
            ViewBag.name = role.Name;
            return View();
        }

        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }

            var result = await _roleManager.DeleteAsync(role);
            if (result.Succeeded)
            {
                TempData["delete"] = "Role has been deleted successfully";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public async Task<IActionResult> Assign()
        {
            ViewData["UserId"] = new SelectList(_userRoleManager.GetUsersIdWithLockout(), "Id", "UserName");
            ViewData["RoleId"] = new SelectList(_roleManager.Roles.ToList(), "Name", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Assign(Dto_Vm_RoleUserVm roleUser)
        {
            var user = _userRoleManager.GetUserById(roleUser.UserId);
            var isCheckRoleAssign = await _userManager.IsInRoleAsync(user, roleUser.RoleId);
            if (isCheckRoleAssign)
            {
                ViewBag.mgs = "This user already assign this role!";
                ViewData["UserId"] = new SelectList(_userRoleManager.GetUsersIdWithLockout(), "Id", "UserName");
                ViewData["RoleId"] = new SelectList(_roleManager.Roles.ToList(), "Name", "Name");
                return View();
            }
            var role = await _userManager.AddToRoleAsync(user, roleUser.RoleId);
            if (role.Succeeded)
            {
                TempData["save"] = "User Role assigned";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public ActionResult AssignUserRole()
        {
            var result = _userRoleManager.GetAssignUsers();
            ViewBag.UserRoles = result;
            return View();
        }
    }
}

OnlineShop/Areas/Customer/Controllers/SearchController.cs
using BusinessLogic.DtoModels;
using BusinessLogic.Interfaces;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Areas.Customer.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace OnlineShop.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class SearchController : Controller
    {
        private readonly IProductManager _productManager;
        private readonly IProductReviewManager _productReviewManager;
        private readonly IProductSpecManager _productSpecManager;
        private readonly IApplicationUserManager _userManager;
        private readonly IProductTypesManager _productTypesManager;

        public SearchController(IProductManager productManager,
            IProductReviewManager productReviewManager,
            IProductSpecManager productSpecManager,
            IApplicationUserManager userManager,
            IProductTypesManager productTypesManager)
        {
            _productManager = productManager;
            _productReviewManager = productReviewManager;
            _productSpecManager = productSpecManager;
            _userManager = userManager;
            _productTypesManager = productTypesManager;
        }

        public async Task<IActionResult> SearchIndex(int? page, string searchString)
        {
            List<Dto_Product> products = _productManager.FindFullProductsThatContainName(searchString).ToList();
            if (products == null)
            {
                return NotFound();
            }
            ViewBag.SearchString = searchString;
            return View(products.ToPagedList(page ?? 1, 5));
        }

        public async Task<IActionResult> Products(int? page)
        {
            var result = _productManager.GetFullProducts().ToPagedList(page ?? 1, 5);
            return View(result);
        }

        public async Task<IActionResult> SearchByProductType(int? page, int? id)
        {
            if (id == null)
                return NotFound();
            var products = _productManager.GetProductsByProductType((int)id).ToList();

            if (products == null)
            {
                return NotFound();
            }

            string type = _productTypesManager.FindProductType(id).ProductType;
            ViewBag.TypeString = type ?? "Category";
            return View(products.ToPagedList(page ?? 1, 5));

        }
    }
}

OnlineShop/Views/Shared/_AntiValidationScriptsPartial.cshtml
<script src="~/js/antiValidation.js"></script>

OnlineShop/Views/Shared/_ButtonPartial.cshtml
@model int

<td style="width: 150px">
    <div class="btn-group">
        <a asp-action="Edit" style="margin-left: 5px" class="btn-primary btn" asp-route-id="@Model">
            <i class="far fa-edit"></i>
        </a>
        <a asp-action="Details" style="margin-left: 5px" class="btn-success btn" asp-route-id="@Model">
            <i class="far fa-list-alt"></i>
        </a>
        <a asp-action="Delete" style="margin-left: 5px" class="btn-danger btn" asp-route-id="@Model">
            <i class="far fa-trash-alt"></i>
        </a>
    </div>
</td>

OnlineShop/Views/Shared/_DeliveryIndexButtonPartial.cshtml
@model int

<td style="width: 150px">
    <div class="btn-group">
        <a asp-action="TakeOrder" style="margin-left: 5px" class="btn-primary btn" asp-route-id="@Model">
            <i class="far fa-edit"></i>
        </a>
        <a asp-action="Details" style="margin-left: 5px" class="btn-success btn" asp-route-id="@Model">
            <i class="far fa-list-alt"></i>
        </a>
    </div>
</td>

OnlineShop/Views/Shared/_FadeInformationPartial.cshtml
<script>
    function fade1() {
        console.log('fade1');
        $('#a1').addClass('active');
        $('#a2').removeClass('active');
        $('#a3').removeClass('active');

        $('#tab1').removeClass('fade');
        $('#tab2').addClass('fade');
        $('#tab3').addClass('fade');

        $('#tab1').addClass('active');
        $('#tab2').removeClass('active');
        $('#tab3').removeClass('active');
    }

    function fade2() {
        console.log('fade2');
        $('#a1').removeClass('active');
        $('#a2').addClass('active');
        $('#a3').removeClass('active');

        $('#tab1').addClass('fade');
        $('#tab2').removeClass('fade');
        $('#tab3').addClass('fade');

        $('#tab1').removeClass('active');
        $('#tab2').addClass('active');
        $('#tab3').removeClass('active');
    }

    function fade3() {
        console.log('fade3');
        $('#a1').removeClass('active');
        $('#a2').removeClass('active');
        $('#a3').addClass('active');

        $('#tab1').addClass('fade');
        $('#tab2').addClass('fade');
        $('#tab3').removeClass('fade');

        $('#tab1').removeClass('active');
        $('#tab2').removeClass('active');
        $('#tab3').addClass('active');
    }
</script>

OnlineShop/Views/Shared/_FlatItemPartial.cshtml
@model BusinessLogic.DtoModels.Dto_Product

<div class="row p-2 bg-white border rounded mt-2">
    <div class="col-md-3 mt-1"><img class="img-fluid img-responsive rounded product-image" src="~/@Model.Image"></div>
    <div class="col-md-6 mt-1">
        <h5>@Model.Name</h5>
        <div class="d-flex flex-row">
            <div class="ratings mr-2"><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i></div><span>REVIEW_COUNT</span>
        </div>
        <div class="mt-1 mb-1 spec-1"><span>100% cotton</span><span class="dot"></span><span>Light weight</span><span class="dot"></span><span>Best finish<br></span></div>
        <div class="mt-1 mb-1 spec-1"><span>Unique design</span><span class="dot"></span><span>For men</span><span class="dot"></span><span>Casual<br></span></div>
        <p class="text-justify text-truncate para mb-0">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.<br><br></p>
    </div>
    <div class="align-items-center align-content-center col-md-3 border-left mt-1">
        <div class="d-flex flex-row align-items-center">
        @if (Model.IsAvailable)
        {
            <h4 class="mr-1">$@Model.Price</h4><span class="strike-text">$@Math.Round(Model.Price + Model.Price * 0.1m, 2)</span>
        }
        </div>
        @if (Model.IsAvailable)
        {
            <h6 class="text-success">Available</h6>
            <div class="d-flex flex-column mt-4">
                <button class="btn btn-primary btn-sm" type="button">Details</button>
                <button class="btn btn-outline-primary btn-sm mt-2" type="button">Add to wishlist</button>
            </div>
        }
        else
        {
            <h6 style="margin-top: 25%" class="text-danger">Out of stock</h6> 
        }
                    
    </div>
</div>

OnlineShop/Views/Shared/_Layout.cshtml
@using System.Net.Http
@using Microsoft.AspNetCore.Identity
@using OnlineShop.Models
@using OnlineShop.Utility
@using Microsoft.AspNetCore.Http
@using BusinessLogic.DtoModels
@using System.Diagnostics
@using System.Security.Claims
@inject IHttpContextAccessor HttpContextAccessor
@{
    var userRole = HttpContextAccessor.HttpContext.Session.GetString("roleName");
    int cartCount = 0;
    int wishCount = 0;
    List<Dto_Product> products = HttpContextAccessor.HttpContext.Session.Get<List<Dto_Product>>("products");
    if (products == null)
    {
        products = new List<Dto_Product>();
    }
    cartCount = products.Count();

    List<Dto_Product> wishlist = HttpContextAccessor.HttpContext.Session.Get<List<Dto_Product>>("wishlist");
    if (wishlist == null)
    {
        wishlist = new List<Dto_Product>();
    }
    wishCount = wishlist.Count();
    var t1 = HttpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.Role);

    var currentRole = t1 != null ? t1.Value : null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=8" />
    <title>@ViewData["Title"] - OnlineShop</title>

    <link rel="stylesheet" href="~/css/site.css" />

    <!-- Font Awesome -->
	<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />

    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.0.0/mdb.min.css" rel="stylesheet" />

	<!-- responsive style -->
	<link rel="stylesheet" type="text/css" href="css/responsive.css" />

    <link rel="stylesheet" type="text/css" href="~/css/slick.css"/>
 	<link rel="stylesheet" type="text/css" href="~/css/slick-theme.css"/>
    <link rel="stylesheet" type="text/css" href="~/css/nouislider.min.css"/>

    <link rel="stylesheet" type="text/css" href="~/css/styleproducts.css"/>
    <link rel="stylesheet" type="text/css" href="~/css/stylenew.css"/>
    
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css"/>

    
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css"/>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/bootstrap.min.css"/>


    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/2.2.2/css/buttons.dataTables.min.css"/>
    
    <link rel="stylesheet" text="text/css" href="~/css/site.css" />
    <link rel="stylesheet" type="text/css" href="~/css/header.css" />

    <style>
        .error{
            color: red;
        }

        .body-container {
            /*remove the container default padding attribute*/
            padding-left: 0px !important;
            padding-right: 0px !important;
            /*increase width as per your need*/
            max-width: 71%;
        } 
    </style>
</head>


<body style="background-color: #fff">
    <header>
        <nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse bg-light" >
            <div class="position-sticky" >
                <div class="list-group list-group-flush mx-3 mt-4">

                    

                    <a asp-area="Customer" asp-controller="Home" asp-action="Index"
                    class="list-group-item bg-light list-group-item-action py-2 ripple" aria-current="true">
                        <i class="fas fa-chart-bar fa-fw me-3"></i>
                        <span>Home</span>
                    </a>


                    <a href="#"
                    class="list-group-item bg-light list-group-item-action py-2 ripple" aria-current="false">
                        <i class="fas fa-chart-bar fa-fw me-3"></i>
                        <span>About us</span>
                    </a>


                    <a asp-area="Customer" asp-controller="Search" asp-action="Products"
                    class="list-group-item bg-light list-group-item-action py-2 ripple" aria-current="false">
                        <i class="fas fa-chart-bar fa-fw me-3"></i>
                        <span>Product list</span>
                    </a>

                    @if (userRole == "Admin" || currentRole == "Admin")
                    {
                        <hr />

                        <a asp-area="Admin" asp-controller="ProductTypes" asp-action="Index" 
                        class="list-group-item bg-light list-group-item-action py-2 ripple" aria-current="false">
                        <i class="fas fa-bars fa-fw me-3"></i>
                        <span>Product types</span></a>

                        <a asp-area="Admin" asp-controller="SpecialTag" asp-action="Index" 
                        class="list-group-item bg-light list-group-item-action py-2 ripple" aria-current="false">
                        <i class="fas fa-bars fa-fw me-3"></i>
                        <span>Tags</span></a>

                        <a asp-area="Admin" asp-controller="Product" asp-action="Index" 
                        class="list-group-item bg-light list-group-item-action py-2 ripple" aria-current="false">
                        <i class="fas fa-box-archive fa-fw me-3"></i>
                        <span>Product types</span></a>

                        <a asp-area="Admin" asp-controller="Role" asp-action="Index" 
                        class="list-group-item bg-light list-group-item-action py-2 ripple" aria-current="false">
                        <i class="fas fa-chain fa-fw me-3"></i>
                        <span>Roles</span></a>

                        <a asp-area="Admin" asp-controller="Role" asp-action="AssignUserRole" 
                        class="list-group-item bg-light list-group-item-action py-2 ripple" aria-current="false">
                        <i class="fas fa-user fa-fw me-3"></i>
                        <span>Users</span></a>
                    }

                    @if (userRole == "Delivery" || currentRole == "Delivery")
                    {
                        <hr />
                        <a asp-area="Delivery" asp-controller="Delivery" asp-action="Index" 
                        class="list-group-item bg-light list-group-item-action py-2 ripple" aria-current="false">
                        <i class="fas fa-truck fa-fw me-3"></i>
                        <span>Delivery</span></a>


                        <a asp-area="Delivery" asp-controller="Delivery" asp-action="MyOrders" 
                        class="list-group-item bg-light list-group-item-action py-2 ripple" aria-current="false">
                        <i class="fas fa-address-book fa-fw me-3"></i>
                        <span>Delivered orders</span></a>
                    }

                    @if (currentRole != null)
                    {
                        <hr />
                        <a asp-area="Identity" asp-page="/Account/Manage/Index"
                        class="list-group-item bg-light list-group-item-action py-2 ripple" aria-current="false">
                        <i class="fas fa-user fa-fw me-3"></i>
                        <span>My Proffile</span></a>

                        <a asp-area="Customer" asp-controller="Order" asp-action="MyOrders"
                        class="list-group-item bg-light list-group-item-action py-2 ripple" aria-current="false">
                        <i class="fas fa-clipboard-list fa-fw me-3"></i>
                        <span>My Orders</span></a>
                    }

                    <p class="list-group-item bg-light list-group-item-action py-2 ripple">Status - @currentRole</p>
                </div>
            </div>
        </nav>


        <nav id="main-navbar" class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-lable="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>

                <a class="navbar-brand text-primary" asp-area="Customer" asp-controller="Home" asp-action="Index">
                    OnlineShop
                </a>

                <form asp-controller="Search" asp-action="SearchIndex" asp-area="Customer"
                    class="d-none d-md-flex input-group w-auto my-auto">
                    <input type="hidden" name="page" value="1"/>
                    <input autocomplete="off" type="search" name="searchString" class="form-control rounded"
                    placeholder='Search here...' style="margin-left: 40px; min-width: 350px;" />
                    <span class="input-group-text border-0"><i class="fas fa-search"></i></span>
                </form>

                <ul class="navbar-nav ms-auto d-flex flex-row">
                    <li class="nav-item">
                        <a asp-area="Customer" asp-controller="Order" asp-action="Checkout" method="get"
                        class="nav-link me-3 me-lg-0">
                            <i class="fas fa-cart-shopping icon-2x"></i>
                            <span id="cartBadge" class="badge rounded-pill badge-notification bg-danger">@cartCount</span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a asp-area="Customer" asp-controller="Home" asp-action="Wishlist" method="get"
                        class="nav-link me-3 me-lg-0">
                            <i class="fas fa-heart icon-2x"></i>
                            <span id="wishlistBadge" class="badge rounded-pill badge-notification bg-danger">@wishCount</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <partial name="_LoginPartial"/>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    
    
    <div style="margin-top: 70px " class="container body-container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

	<br/><br/>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - OnlineShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    

    <!-- jQuery -->
	<script src="~/js/jquery.min.js"></script>
    <script src="~/js/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    
    <!-- MDB -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.0.0/mdb.min.js"></script>

	<script src="~/js/slick.min.js"></script>
	<script src="~/js/nouislider.min.js"></script>
	<script src="~/js/jquery.zoom.min.js"></script>
	<script src="~/js/main.js"></script>

    <script src="~/js/custom.js"></script>

	<script src="~/js/site.js" asp-append-version="true"></script>

    <script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.2/js/buttons.print.min.js"></script>

	<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>